image: cirrusci/flutter:2.10.0

stages:
  - build
  - deploy

before_script:
  - flutter pub get

flutter_build:
  stage: build
  script:
    - flutter build web --release
  artifacts:
    paths:
      - build/web/

deploy_to_gitlab_pages:
  stage: deploy
  script:
    - mv build/web/ public/
  artifacts:
    paths:
      - public
  only:
    - master
